var searchData=
[
  ['featurefield',['FeatureField',['../db/d00/classorg_1_1apache_1_1lucene_1_1document_1_1_feature_field.html',1,'org::apache::lucene::document']]],
  ['field',['Field',['../d0/d8b/classorg_1_1apache_1_1lucene_1_1document_1_1_field.html',1,'org::apache::lucene::document']]],
  ['fieldcomparator',['FieldComparator',['../db/d2b/classorg_1_1apache_1_1lucene_1_1search_1_1_field_comparator.html',1,'org::apache::lucene::search']]],
  ['fieldcomparator_3c_20bytesref_20_3e',['FieldComparator&lt; BytesRef &gt;',['../db/d2b/classorg_1_1apache_1_1lucene_1_1search_1_1_field_comparator.html',1,'org::apache::lucene::search']]],
  ['fieldcomparator_3c_20double_20_3e',['FieldComparator&lt; Double &gt;',['../db/d2b/classorg_1_1apache_1_1lucene_1_1search_1_1_field_comparator.html',1,'org::apache::lucene::search']]],
  ['fieldcomparator_3c_20float_20_3e',['FieldComparator&lt; Float &gt;',['../db/d2b/classorg_1_1apache_1_1lucene_1_1search_1_1_field_comparator.html',1,'org::apache::lucene::search']]],
  ['fieldcomparator_3c_20integer_20_3e',['FieldComparator&lt; Integer &gt;',['../db/d2b/classorg_1_1apache_1_1lucene_1_1search_1_1_field_comparator.html',1,'org::apache::lucene::search']]],
  ['fieldcomparator_3c_3f_3e',['FieldComparator&lt;?&gt;',['../db/d2b/classorg_1_1apache_1_1lucene_1_1search_1_1_field_comparator.html',1,'org::apache::lucene::search']]],
  ['fieldcomparatorsource',['FieldComparatorSource',['../d3/daf/classorg_1_1apache_1_1lucene_1_1search_1_1_field_comparator_source.html',1,'org::apache::lucene::search']]],
  ['fielddoc',['FieldDoc',['../db/db5/classorg_1_1apache_1_1lucene_1_1search_1_1_field_doc.html',1,'org::apache::lucene::search']]],
  ['fieldinfo',['FieldInfo',['../d4/dcb/classorg_1_1apache_1_1lucene_1_1index_1_1_field_info.html',1,'org::apache::lucene::index']]],
  ['fieldinfos',['FieldInfos',['../d4/db4/classorg_1_1apache_1_1lucene_1_1index_1_1_field_infos.html',1,'org::apache::lucene::index']]],
  ['fieldinfosformat',['FieldInfosFormat',['../d9/d2b/classorg_1_1apache_1_1lucene_1_1codecs_1_1_field_infos_format.html',1,'org::apache::lucene::codecs']]],
  ['fieldinvertstate',['FieldInvertState',['../d9/dfa/classorg_1_1apache_1_1lucene_1_1index_1_1_field_invert_state.html',1,'org::apache::lucene::index']]],
  ['fieldmaskingspanquery',['FieldMaskingSpanQuery',['../dd/df2/classorg_1_1apache_1_1lucene_1_1search_1_1spans_1_1_field_masking_span_query.html',1,'org::apache::lucene::search::spans']]],
  ['fieldreader',['FieldReader',['../d4/dd9/classorg_1_1apache_1_1lucene_1_1codecs_1_1blocktree_1_1_field_reader.html',1,'org::apache::lucene::codecs::blocktree']]],
  ['fields',['Fields',['../d5/d65/classorg_1_1apache_1_1lucene_1_1index_1_1_fields.html',1,'org::apache::lucene::index']]],
  ['fieldsconsumer',['FieldsConsumer',['../d8/d77/classorg_1_1apache_1_1lucene_1_1codecs_1_1_fields_consumer.html',1,'org::apache::lucene::codecs']]],
  ['fieldsproducer',['FieldsProducer',['../db/dfb/classorg_1_1apache_1_1lucene_1_1codecs_1_1_fields_producer.html',1,'org::apache::lucene::codecs']]],
  ['fieldtype',['FieldType',['../de/d8a/classorg_1_1apache_1_1lucene_1_1document_1_1_field_type.html',1,'org::apache::lucene::document']]],
  ['fieldvaluehitqueue',['FieldValueHitQueue',['../d4/daa/classorg_1_1apache_1_1lucene_1_1search_1_1_field_value_hit_queue.html',1,'org::apache::lucene::search']]],
  ['fieldvaluehitqueue_3c_20entry_20_3e',['FieldValueHitQueue&lt; Entry &gt;',['../d4/daa/classorg_1_1apache_1_1lucene_1_1search_1_1_field_value_hit_queue.html',1,'org::apache::lucene::search']]],
  ['fieldvaluehitqueue_3c_20t_20_3e',['FieldValueHitQueue&lt; T &gt;',['../d4/daa/classorg_1_1apache_1_1lucene_1_1search_1_1_field_value_hit_queue.html',1,'org::apache::lucene::search']]],
  ['fileswitchdirectory',['FileSwitchDirectory',['../d7/d7f/classorg_1_1apache_1_1lucene_1_1store_1_1_file_switch_directory.html',1,'org::apache::lucene::store']]],
  ['filterbinarydocvalues',['FilterBinaryDocValues',['../d5/d23/classorg_1_1apache_1_1lucene_1_1index_1_1_filter_binary_doc_values.html',1,'org::apache::lucene::index']]],
  ['filtercodec',['FilterCodec',['../d2/d2d/classorg_1_1apache_1_1lucene_1_1codecs_1_1_filter_codec.html',1,'org::apache::lucene::codecs']]],
  ['filtercodecreader',['FilterCodecReader',['../da/d14/classorg_1_1apache_1_1lucene_1_1index_1_1_filter_codec_reader.html',1,'org::apache::lucene::index']]],
  ['filtercollector',['FilterCollector',['../d7/d79/classorg_1_1apache_1_1lucene_1_1search_1_1_filter_collector.html',1,'org::apache::lucene::search']]],
  ['filterdirectory',['FilterDirectory',['../d7/d14/classorg_1_1apache_1_1lucene_1_1store_1_1_filter_directory.html',1,'org::apache::lucene::store']]],
  ['filterdirectoryreader',['FilterDirectoryReader',['../d0/dfc/classorg_1_1apache_1_1lucene_1_1index_1_1_filter_directory_reader.html',1,'org::apache::lucene::index']]],
  ['filtereddocidsetiterator',['FilteredDocIdSetIterator',['../d3/d89/classorg_1_1apache_1_1lucene_1_1search_1_1_filtered_doc_id_set_iterator.html',1,'org::apache::lucene::search']]],
  ['filteredtermsenum',['FilteredTermsEnum',['../d6/d25/classorg_1_1apache_1_1lucene_1_1index_1_1_filtered_terms_enum.html',1,'org::apache::lucene::index']]],
  ['filteringtokenfilter',['FilteringTokenFilter',['../dd/d79/classorg_1_1apache_1_1lucene_1_1analysis_1_1_filtering_token_filter.html',1,'org::apache::lucene::analysis']]],
  ['filteriterator',['FilterIterator',['../da/db8/classorg_1_1apache_1_1lucene_1_1util_1_1_filter_iterator.html',1,'org::apache::lucene::util']]],
  ['filterleafcollector',['FilterLeafCollector',['../df/d42/classorg_1_1apache_1_1lucene_1_1search_1_1_filter_leaf_collector.html',1,'org::apache::lucene::search']]],
  ['filterleafreader',['FilterLeafReader',['../df/d2d/classorg_1_1apache_1_1lucene_1_1index_1_1_filter_leaf_reader.html',1,'org::apache::lucene::index']]],
  ['filtermatchesiterator',['FilterMatchesIterator',['../d4/dd8/classorg_1_1apache_1_1lucene_1_1search_1_1_filter_matches_iterator.html',1,'org::apache::lucene::search']]],
  ['filtermergepolicy',['FilterMergePolicy',['../d5/d8a/classorg_1_1apache_1_1lucene_1_1index_1_1_filter_merge_policy.html',1,'org::apache::lucene::index']]],
  ['filternumericdocvalues',['FilterNumericDocValues',['../d6/ddd/classorg_1_1apache_1_1lucene_1_1index_1_1_filter_numeric_doc_values.html',1,'org::apache::lucene::index']]],
  ['filterscorable',['FilterScorable',['../de/d40/classorg_1_1apache_1_1lucene_1_1search_1_1_filter_scorable.html',1,'org::apache::lucene::search']]],
  ['filterscorer',['FilterScorer',['../d2/dd2/classorg_1_1apache_1_1lucene_1_1search_1_1_filter_scorer.html',1,'org::apache::lucene::search']]],
  ['filterspans',['FilterSpans',['../d0/db3/classorg_1_1apache_1_1lucene_1_1search_1_1spans_1_1_filter_spans.html',1,'org::apache::lucene::search::spans']]],
  ['filterweight',['FilterWeight',['../d9/d79/classorg_1_1apache_1_1lucene_1_1search_1_1_filter_weight.html',1,'org::apache::lucene::search']]],
  ['finitestringsiterator',['FiniteStringsIterator',['../d8/d1f/classorg_1_1apache_1_1lucene_1_1util_1_1automaton_1_1_finite_strings_iterator.html',1,'org::apache::lucene::util::automaton']]],
  ['fixedbitset',['FixedBitSet',['../dc/da5/classorg_1_1apache_1_1lucene_1_1util_1_1_fixed_bit_set.html',1,'org::apache::lucene::util']]],
  ['flagsattribute',['FlagsAttribute',['../d0/daa/interfaceorg_1_1apache_1_1lucene_1_1analysis_1_1tokenattributes_1_1_flags_attribute.html',1,'org::apache::lucene::analysis::tokenattributes']]],
  ['flagsattributeimpl',['FlagsAttributeImpl',['../d8/d95/classorg_1_1apache_1_1lucene_1_1analysis_1_1tokenattributes_1_1_flags_attribute_impl.html',1,'org::apache::lucene::analysis::tokenattributes']]],
  ['floatdocvaluesfield',['FloatDocValuesField',['../d4/d62/classorg_1_1apache_1_1lucene_1_1document_1_1_float_doc_values_field.html',1,'org::apache::lucene::document']]],
  ['floatpoint',['FloatPoint',['../da/d6e/classorg_1_1apache_1_1lucene_1_1document_1_1_float_point.html',1,'org::apache::lucene::document']]],
  ['floatrange',['FloatRange',['../d3/d93/classorg_1_1apache_1_1lucene_1_1document_1_1_float_range.html',1,'org::apache::lucene::document']]],
  ['flushinfo',['FlushInfo',['../d9/de6/classorg_1_1apache_1_1lucene_1_1store_1_1_flush_info.html',1,'org::apache::lucene::store']]],
  ['format',['Format',['../d4/de6/enumorg_1_1apache_1_1lucene_1_1util_1_1packed_1_1_packed_ints_1_1_format.html',1,'org::apache::lucene::util::packed::PackedInts']]],
  ['frequencytrackingringbuffer',['FrequencyTrackingRingBuffer',['../d3/d64/classorg_1_1apache_1_1lucene_1_1util_1_1_frequency_tracking_ring_buffer.html',1,'org::apache::lucene::util']]],
  ['fsa',['FSA',['../d6/d15/class_u_t_f32_to_u_t_f8_1_1_f_s_a.html',1,'UTF32ToUTF8']]],
  ['fsdirectory',['FSDirectory',['../d0/df5/classorg_1_1apache_1_1lucene_1_1store_1_1_f_s_directory.html',1,'org::apache::lucene::store']]],
  ['fslockfactory',['FSLockFactory',['../d1/dd0/classorg_1_1apache_1_1lucene_1_1store_1_1_f_s_lock_factory.html',1,'org::apache::lucene::store']]],
  ['fst',['FST',['../d2/de5/classorg_1_1apache_1_1lucene_1_1util_1_1fst_1_1_f_s_t.html',1,'org::apache::lucene::util::fst']]],
  ['fst_3c_20org_3a_3aapache_3a_3alucene_3a_3autil_3a_3abytesref_20_3e',['FST&lt; org::apache::lucene::util::BytesRef &gt;',['../d2/de5/classorg_1_1apache_1_1lucene_1_1util_1_1fst_1_1_f_s_t.html',1,'org::apache::lucene::util::fst']]],
  ['futurearrays',['FutureArrays',['../d3/da3/classorg_1_1apache_1_1lucene_1_1util_1_1_future_arrays.html',1,'org::apache::lucene::util']]],
  ['futureobjects',['FutureObjects',['../d6/deb/classorg_1_1apache_1_1lucene_1_1util_1_1_future_objects.html',1,'org::apache::lucene::util']]],
  ['fuzzyquery',['FuzzyQuery',['../de/dc5/classorg_1_1apache_1_1lucene_1_1search_1_1_fuzzy_query.html',1,'org::apache::lucene::search']]],
  ['fuzzytermsenum',['FuzzyTermsEnum',['../d5/d1a/classorg_1_1apache_1_1lucene_1_1search_1_1_fuzzy_terms_enum.html',1,'org::apache::lucene::search']]]
];
