var searchData=
[
  ['radixselector',['RadixSelector',['../d9/d49/classorg_1_1apache_1_1lucene_1_1util_1_1_radix_selector.html',1,'org::apache::lucene::util']]],
  ['ramdirectory',['RAMDirectory',['../d3/da0/classorg_1_1apache_1_1lucene_1_1store_1_1_r_a_m_directory.html',1,'org::apache::lucene::store']]],
  ['ramfile',['RAMFile',['../d3/dbe/classorg_1_1apache_1_1lucene_1_1store_1_1_r_a_m_file.html',1,'org::apache::lucene::store']]],
  ['raminputstream',['RAMInputStream',['../dc/d58/classorg_1_1apache_1_1lucene_1_1store_1_1_r_a_m_input_stream.html',1,'org::apache::lucene::store']]],
  ['ramoutputstream',['RAMOutputStream',['../d3/d9d/classorg_1_1apache_1_1lucene_1_1store_1_1_r_a_m_output_stream.html',1,'org::apache::lucene::store']]],
  ['ramusageestimator',['RamUsageEstimator',['../db/d4e/classorg_1_1apache_1_1lucene_1_1util_1_1_ram_usage_estimator.html',1,'org::apache::lucene::util']]],
  ['randomaccessinput',['RandomAccessInput',['../d0/d78/interfaceorg_1_1apache_1_1lucene_1_1store_1_1_random_access_input.html',1,'org::apache::lucene::store']]],
  ['ratelimitedindexoutput',['RateLimitedIndexOutput',['../d5/d6a/classorg_1_1apache_1_1lucene_1_1store_1_1_rate_limited_index_output.html',1,'org::apache::lucene::store']]],
  ['ratelimiter',['RateLimiter',['../d4/db5/classorg_1_1apache_1_1lucene_1_1store_1_1_rate_limiter.html',1,'org::apache::lucene::store']]],
  ['readermanager',['ReaderManager',['../d4/d05/classorg_1_1apache_1_1lucene_1_1index_1_1_reader_manager.html',1,'org::apache::lucene::index']]],
  ['readerslice',['ReaderSlice',['../d0/df5/classorg_1_1apache_1_1lucene_1_1index_1_1_reader_slice.html',1,'org::apache::lucene::index']]],
  ['readerutil',['ReaderUtil',['../d3/d5d/classorg_1_1apache_1_1lucene_1_1index_1_1_reader_util.html',1,'org::apache::lucene::index']]],
  ['rectangle',['Rectangle',['../da/d43/classorg_1_1apache_1_1lucene_1_1geo_1_1_rectangle.html',1,'org::apache::lucene::geo']]],
  ['recyclingbyteblockallocator',['RecyclingByteBlockAllocator',['../d0/dd5/classorg_1_1apache_1_1lucene_1_1util_1_1_recycling_byte_block_allocator.html',1,'org::apache::lucene::util']]],
  ['recyclingintblockallocator',['RecyclingIntBlockAllocator',['../dd/d18/classorg_1_1apache_1_1lucene_1_1util_1_1_recycling_int_block_allocator.html',1,'org::apache::lucene::util']]],
  ['refcount',['RefCount',['../d5/df2/classorg_1_1apache_1_1lucene_1_1util_1_1_ref_count.html',1,'org::apache::lucene::util']]],
  ['referencemanager',['ReferenceManager',['../d8/d2a/classorg_1_1apache_1_1lucene_1_1search_1_1_reference_manager.html',1,'org::apache::lucene::search']]],
  ['referencemanager_3c_20directoryreader_20_3e',['ReferenceManager&lt; DirectoryReader &gt;',['../d8/d2a/classorg_1_1apache_1_1lucene_1_1search_1_1_reference_manager.html',1,'org::apache::lucene::search']]],
  ['referencemanager_3c_20indexsearcher_20_3e',['ReferenceManager&lt; IndexSearcher &gt;',['../d8/d2a/classorg_1_1apache_1_1lucene_1_1search_1_1_reference_manager.html',1,'org::apache::lucene::search']]],
  ['referencemanager_3c_20s_20_3e',['ReferenceManager&lt; S &gt;',['../d8/d2a/classorg_1_1apache_1_1lucene_1_1search_1_1_reference_manager.html',1,'org::apache::lucene::search']]],
  ['referencemanager_3c_20t_20_3e',['ReferenceManager&lt; T &gt;',['../d8/d2a/classorg_1_1apache_1_1lucene_1_1search_1_1_reference_manager.html',1,'org::apache::lucene::search']]],
  ['refreshlistener',['RefreshListener',['../de/db3/interfaceorg_1_1apache_1_1lucene_1_1search_1_1_reference_manager_1_1_refresh_listener.html',1,'org::apache::lucene::search::ReferenceManager']]],
  ['regexp',['RegExp',['../d2/d9f/classorg_1_1apache_1_1lucene_1_1util_1_1automaton_1_1_reg_exp.html',1,'org::apache::lucene::util::automaton']]],
  ['regexpquery',['RegexpQuery',['../d7/d36/classorg_1_1apache_1_1lucene_1_1search_1_1_regexp_query.html',1,'org::apache::lucene::search']]],
  ['relation',['Relation',['../d0/da4/enumorg_1_1apache_1_1lucene_1_1search_1_1_total_hits_1_1_relation.html',1,'org.apache.lucene.search.TotalHits.Relation'],['../d5/d9d/enumorg_1_1apache_1_1lucene_1_1index_1_1_point_values_1_1_relation.html',1,'org.apache.lucene.index.PointValues.Relation']]],
  ['rescorer',['Rescorer',['../da/d65/classorg_1_1apache_1_1lucene_1_1search_1_1_rescorer.html',1,'org::apache::lucene::search']]],
  ['roaringdocidset',['RoaringDocIdSet',['../d9/dbb/classorg_1_1apache_1_1lucene_1_1util_1_1_roaring_doc_id_set.html',1,'org::apache::lucene::util']]],
  ['rollingbuffer',['RollingBuffer',['../d4/dc0/classorg_1_1apache_1_1lucene_1_1util_1_1_rolling_buffer.html',1,'org::apache::lucene::util']]],
  ['rollingbuffer_3c_20position_20_3e',['RollingBuffer&lt; Position &gt;',['../d4/dc0/classorg_1_1apache_1_1lucene_1_1util_1_1_rolling_buffer.html',1,'org::apache::lucene::util']]],
  ['runautomaton',['RunAutomaton',['../d0/da5/classorg_1_1apache_1_1lucene_1_1util_1_1automaton_1_1_run_automaton.html',1,'org::apache::lucene::util::automaton']]]
];
