# ---------
# For more about configuration of mkdoks and material design theme see:
# - https://squidfunk.github.io/mkdocs-material/
# - https://facelessuser.github.io/pymdown-extensions/
# - https://www.webpagefx.com/tools/emoji-cheat-sheet/
# ---------

site_name: Anatomy of e-Commerce Search
nav:
  - Home: index.md
  - Visual Search: visual_search/vs_index.md
  - Apache Lucene:
    - Guides: lucene-index.md
    - Getting started: getting_started.md
    - Look inside: look_inside.md
    - links.md
    - API: doxygen/lucene-core/

theme:
  name: material
  feature:
    tabs: false

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
